name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  reusable-build-workflow:
    uses: ./.github/workflows/reusable-build-workflow.yaml
    with:
      node-version: "18" # Specify the Node.js version to use
    
    