name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important! semantic-release needs full history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0

      - name: Install dependencies
        run: |
          npm install
          npm ci

      - name: Get next release version
        id: get_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main --no-rebase || true
          npx semantic-release --dry-run | tee sr.log
          version=$(grep -oP 'Release note for version \K[0-9]+\.[0-9]+\.[0-9]+' sr.log | tail -1)
          version=$(grep -oP 'Release note for version \K[0-9]+\.[0-9]+\.[0-9]+' sr.log | tail -1)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create and checkout release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          branch_name=release/v${{ steps.get_version.outputs.version }}
          echo "Creating and checking out branch: $branch_name"
          if git ls-remote --exit-code --heads origin "$branch_name"; then
            git push origin --delete "$branch_name" || true
            git branch -D "$branch_name" || true
            git checkout -b "$branch_name"
            git push origin "$branch_name"
          else
            git checkout -b "$branch_name"
            git push origin "$branch_name"
          fi

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $current_branch"
          echo "Running semantic-release on branch: $branch_name"
          npx semantic-release

      - name: Create Pull Request to main
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release v${{ steps.get_version.outputs.version }}"
          title: "Release v${{ steps.get_version.outputs.version }}"
          body: "Automated PR to merge release/v${{ steps.get_version.outputs.version }} into main"
          base: main
          head: release/v${{ steps.get_version.outputs.version }}
          draft: false

      - name: Auto-merge Pull Request
        if: steps.create_pr.outputs.pull-request-number != ''
        run: |
          pr_number=${{ steps.create_pr.outputs.pull-request-number }}
          gh pr merge "$pr_number" --squash --admin --delete-branch
